# Generated by Django 3.1.7 on 2021-05-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testAPIapp', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('class_student', models.CharField(max_length=2)),
                ('age', models.IntegerField(blank=True)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('rating', models.CharField(choices=[('excellent', 5), ('average', 4), ('bad', 2)], default='average', max_length=50)),
            ],
            options={
                'ordering': ['uploaded'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('teacher', models.CharField(max_length=100)),
                ('uspevaemost', models.CharField(choices=[('excellent', 5), ('average', 4), ('bad', 2)], default='average', max_length=50)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='pictures/')),
            ],
            options={
                'ordering': ['add_date'],
            },
        ),
        migrations.DeleteModel(
            name='DRFPost',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
